// Writes public/player/icons.js: the Lucide icons (ISC) the scene API offers through S.icon(name).
// Keep the list in step with videoRuntimeDoc in backend/internal/service/video_prompts.go.
import { writeFileSync } from 'node:fs'

const names = `brain cpu database server cloud globe rocket zap shield lock key user users heart star check x
alert-triangle lightbulb book-open graduation-cap flask-conical atom dna chart-bar chart-line chart-pie trending-up
clock calendar map-pin car plane phone smartphone laptop monitor camera music mic message-circle mail search settings
code terminal git-branch layers box package gift dollar-sign shopping-cart sun moon leaf flame droplet mountain home
building flag target trophy play arrow-right arrow-up arrow-down refresh-cw sparkles eye hand thumbs-up wifi battery circle`
  .split(/\s+/)
  .filter(Boolean)

// Lucide renamed a few icons; try the aliases.
const aliases = { 'alert-triangle': 'triangle-alert', 'chart-bar': 'chart-column', home: 'house', 'flask-conical': 'flask-conical' }
const out = {}
for (const name of names) {
  let mod
  for (const file of [name, aliases[name]].filter(Boolean)) {
    try {
      mod = await import(`lucide/dist/esm/icons/${file}.js`)
      break
    } catch {}
  }
  if (!mod) {
    console.warn('missing icon', name)
    continue
  }
  out[name] = mod.default[2].map(([tag, attrs]) => [tag, attrs])
}
writeFileSync(new URL('../public/player/icons.js', import.meta.url), `/* Lucide icons (ISC license) for S.icon — generated by scripts/gen-icons.mjs */\nwindow.__FILM_ICONS__ = ${JSON.stringify(out)};\n`)
console.log('icons:', Object.keys(out).length)
